name: github-pages

on:
  push:
    branches:
      - legacy

jobs:
  build-deploy:
    name: Build and deploy the demo site to GitHub Pages
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - run: yarn install

      - name: Build
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          keep_files: true
          publish_branch: gh-pages
          publish_dir: ./docs
          destination_dir: legacy
