name: github-pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and deploy the demo site to GitHub Pages
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm install

      - name: Build
        run: npm run build:site

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          keep_files: true
          publish_branch: gh-pages
          publish_dir: ./dist
