name: tests
on: [push, pull_request]
jobs:
  lint_test_upload-coverage:
    name: Lint, test and upload coverage
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - run: yarn install

      - name: Check for lint errors
        run: yarn lint --no-fix

      - name: Run tests
        if: success()
        run: yarn test:coverage

      - name: Upload coverage
        if: success()
        run: bash <(curl -s https://codecov.io/bash) -t $TOKEN -B $REF
        env:
          TOKEN: "${{ secrets.CODECOV_TOKEN }}"
          REF: "${{ github.ref }}"
