name: tests
on: [push, pull_request]
jobs:
  lint_test_upload-coverage:
    name: Lint, test and upload coverage
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm install

      - name: Check for linting errors
        run: npm run lint

      - name: Run tests
        if: success()
        run: yarn test

      - name: Upload coverage
        if: success()
        run: bash <(curl -s https://codecov.io/bash) -t $TOKEN -B $REF
        env:
          TOKEN: "${{ secrets.CODECOV_TOKEN }}"
          REF: "${{ github.ref }}"
